services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql
    platform: linux/amd64
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: